repos:
    -   repo: https://github.com/PyCQA/isort
        rev: '5.9.1'
        hooks:
            -   id: isort

    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: 'v1.5.7'
        hooks:
            -   id: autopep8

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
            -   id: trailing-whitespace
            -   id: check-yaml
            -   id: requirements-txt-fixer

    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.26.0
        hooks:
            -   id: pyupgrade
                args: [ '--py3-plus', '--py36-plus' ]
