exclude: "Hardware/heart-rate-sensor/.pio/libdeps/"
repos:
  - repo: https://github.com/PyCQA/isort
    rev: "5.9.1"
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.5.7"
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: file-contents-sorter
        args:
          [
            ".github/codespell/allow-words.txt",
            ".github/codespell/custom-dictionary.txt",
          ]
      - id: trailing-whitespace
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: ["--py3-plus", "--py36-plus"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["-D", "-"]
