name: docker image build

on:
  push:
    branches:
      - 'main'
      - 'rica-docker-deploy'
      - 'backend-docker'
      - 'front-end-docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build & push backend
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: teamrocketballeballe/rica-backend:latest
      -
        name: Build & push frontend
        continue-on-error: true
        uses: docker/build-push-action@v2
        with:
          context: ./front-end
          push: true
          tags: teamrocketballeballe/rica-frontend:latest
