name: Pytest

on:
  push:
    paths:
        - "**.py"
  pull_request:
    paths:
        - "**.py"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      RICA_MYSQL_DB: rica
      RICA_MYSQL_USER: root
      RICA_MYSQL_PASSWORD: 'root'
      RICA_MYSQL_HOST: localhost

    steps:
    - name: Start MySQL
      run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -e 'SHOW DATABASES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest
